openapi: 3.0.0
info:
  title: Simple Post API
  version: '1.0'
  contact:
    name: Mckay
  description: Just a simple api for exploration
servers:
  - url: 'http://localhost:3000'
paths:
  /post:
    get:
      summary: Get all Posts
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/post.v1.json
      description: Gets an array of Posts
      operationId: getPosts
    post:
      summary: Create new Post
      responses:
        '201':
          description: Created
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/post.v1.json
        description: The body is the Post to create
      description: Creates a new Post
    parameters: []
  '/post/{postId}':
    parameters:
      - type: string
        name: postId
        in: path
        description: Id of the post to get
        schema:
          type: string
        required: true
    get:
      summary: Get specific post
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/post.v1.json
            application/xml:
              schema:
                $ref: ./models/post.v1.json
      description: Get post by Post ID
    put:
      summary: Update
      responses:
        '204':
          description: No Content
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/post.v1.json
        description: ''
      description: Updates post given an ID
    delete:
      summary: Delete
      responses:
        '204':
          description: No Content
      description: Removes a post given a specific ID
      parameters: []
components:
  schemas: {}
